# Generated by Django 3.1.3 on 2020-11-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('terminal_id', models.CharField(default='0001 : 05', max_length=200)),
                ('clas', models.CharField(default='User', max_length=200, verbose_name='class')),
                ('mode', models.CharField(default='Access', max_length=200)),
                ('types', models.CharField(default='User', max_length=200, verbose_name='type')),
                ('result', models.CharField(default='Success', max_length=200)),
                ('property', models.IntegerField(default=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.user')),
            ],
        ),
    ]
